### ISSUE TITLE
Vagrant Up fails

### ISSUE THREAD

**Issue by sashank** [intrigueio/intrigue-core#70]
I get the below error message when i ran vagrant up

 ```
  intrigue-core: [+] Installing Ruby 2.4.0
    intrigue-core: ruby-build: definition not found: 2.4.0
    intrigue-core:
    intrigue-core: See all available versions with `rbenv install --list'.
    intrigue-core:
    intrigue-core: If the version you need is missing, try upgrading ruby-build
    intrigue-core: :
    intrigue-core:
    intrigue-core:   cd /home/vagrant/.rbenv/plugins/ruby-build && git pull && cd -
' not installedre: rbenv: version `2.4.0
    intrigue-core: /tmp/vagrant-shell: line 93: gem: command not found
    intrigue-core: /tmp/vagrant-shell: line 102: bundle: command not found
    intrigue-core: [+] Migrating database
    intrigue-core: /tmp/vagrant-shell: line 105: bundle: command not found
    intrigue-core: [+] Creating intrigue service
    intrigue-core: chmod: cannot access '/core/util/control.sh': No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
